name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+4
  geolocator: ^9.0.2
  permission_handler: ^10.4.0
  url_launcher: ^6.1.7
  flutter_windowmanager: ^0.2.0
  sqflite: ^2.2.7+1
  path: ^1.8.3
  bcrypt: 1.1.3
  crypt: ^4.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
